### ISSUE TITLE
pad function claims by column doesn't exist in dataframe

### ISSUE THREAD

**Issue by doug-friedman** [EdwinTh/padr#11]
The below code worked in padr 0.1.0, but breaks in padr 0.2.0. The issue seems to be that the new version of the pad function cannot identify that my by column name is in my dataframe.

```R
library(magrittr)
library(padr)

sample_df = data.frame(
            dates = as.Date(c("1946-03-28", "1947-03-25", "1950-04-17")),
            data = c(120, 665, 2001))

sample_df2 = sample_df %>% thicken(interval="year", by="dates", colname="even_dates")

sample_df2 %>% pad(interval="year", by="even_dates")
# I get this error -> Error: by name not found in the column names
```

To help diagnose the issue, I ran the pad (and check_date_variable) functions from scratch and traced back the error.

```R
library(magrittr)
#library(padr)

source("pad.R")
source("check_date_variables.R")

sample_df = data.frame(
            dates = as.Date(c("1946-03-28", "1947-03-25", "1950-04-17")),
            data = c(120, 665, 2001))

sample_df2 = sample_df %>% thicken(interval="year", by="dates", colname="even_dates")
sample_df2

sample_df2 %>% pad(interval="year", by="even_dates")
traceback()
#12: stop("by name not found in the column names", call. = FALSE) at check_date_variables.R#13
#11: check_data_frame(x, by = by_val) at pad.R#118
#10: pad_single(x, interval = interval, start_val = start_val, end_val = end_val, 
#        by = by, group = NULL) at pad.R#75
#9: pad(., interval = "year", by = "even_dates")
#8: function_list[[k]](value)
#7: withVisible(function_list[[k]](value))
#6: freduce(value, `_function_list`)
#5: `_fseq`(`_lhs`)
#4: eval(expr, envir, enclos)
#3: eval(quote(`_fseq`(`_lhs`)), env, env)
#2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
#1: sample_df2 %>% pad(interval = "year", by = "even_dates")
```

I added a little debug printing and I think the issue is that your use of match.call within the pad_single function is not returning the original function's arguments because it's nested within the pad function. Instead, it's just returning the names used when you passed those arguments to pad_single (e.g. by_val is not the name of the column but literally a string "by").

```R
> sample_df2 %>% pad(interval="year", by="even_dates")
# For reference, debug printing is happening right after Line 112 in pad.R
[1] "arguments"
[[1]]
pad_single

$x
x

$interval
interval

$start_val
start_val

$end_val
end_val

$by
by

$group
NULL

[1] "by"
[1] "even_dates"
[1] "by_val"
[1] "by"

```

**Comment by EdwinTh** [comment]
Hi Doug. That is an extremely helpful Issue post! Thanks a lot! Bit sloppy of mine not to test it on pad level, but only on pad_single. Sorry for that. Will fix it asap.

**Comment by doug-friedman** [comment]
@EdwinTh - No problem! This library has been a huge help to me for dealing with non-standard date intervals and I'm happy to pay it forward.

**Comment by EdwinTh** [comment]
Glad to hear, thanks for letting me know. I think I got it all fixed now. Only still a bit in a fight with the unit tests that give errors that seem unrelated to the working of the code. Could you maybe do a devtools::install_github of this version and check if all your old code is working again? That would reassure me that the failing tests are unrelated to fix. Cheers.

**Comment by doug-friedman** [comment]
That worked! Now I get the following:

```R
> sample_df2 %>% pad(interval="year", by="even_dates")
#  even_dates      dates data
#1 1946-01-01 1946-03-28  120
#2 1947-01-01 1947-03-25  665
#3 1948-01-01       <NA>   NA
#4 1949-01-01       <NA>   NA
#5 1950-01-01 1950-04-17 2001
```

**Comment by EdwinTh** [comment]
Last minor bugs are fixed, going to do some testing tomorrow and then it will go to CRAN.
