### ISSUE TITLE
fill_by_ should get a quoted version, like the main dplyr functions

### ISSUE THREAD

**Issue by EdwinTh** [EdwinTh/padr#15]
Now we can only use the unquoted variable names, there should also be a version at which the user can give a character vector.

**Comment by rgknight** [comment]
I believe that the tidyverse is moving away from `mutate_` style functions? See the **tidyeval** framework here https://github.com/tidyverse/rlang

**Comment by EdwinTh** [comment]
Thanks for pointing that out, will wait and see what the developments are.

**Comment by EdwinTh** [comment]
No longer necessary because of the introduction of `tidyeval`
