### ISSUE TITLE
Error of 'by' argument when `thicken` is called by another function.

### ISSUE THREAD

**Issue by hongyuanjia** [EdwinTh/padr#17]
Hi @EdwinTh , thank you so much for this amazing package!

I ran into an error when trying to call `thicken` in my own function, for example:
```{r}
example <- function (x, interval, by) {
    x <- thicken(x = x, interval = interval, by = by)
    return(x)
}

try <- data.table(datetime = seq(as.Date("2017-04-01"),
                                 as.Date("2017-04-05"),
                                 by = "day"),
                  x = seq(1:5))
```
It will always give an error complaining 'by' name not found.
```{r}
example(try, interval = "year")
# Error: by name not found in the column names.

example(try, interval = "year", by = "datetime")
# Error: by name not found in the column names.
```
After traceback, I found that this is because the code blow in `thicken.R`:
```{r}
if (!missing(by)) by_val <- as.character(arguments$by) else by_val <- NULL
```
will convert the value of `by` to a character, e.g. in the `example` case, the `by` that is passed to `check_data_frame` will always be a character "**by**".

Let's give a try if this is true:
```{r}
example_by <- function(by = NULL) {

  arguments <- as.list(match.call())

  if (!missing(by)) by_val <- as.character(arguments$by) else by_val <- NULL

  return(by_val)
}

example_by2 <- function (by = NULL) {
    example_by(by = by)
}

example_by2()
# [1] "by"
example_by2(by = "abc")
# [1] "by"
```
This makes it hard to call `thicken` in other function. Please fix.

Thanks again for your amazing work!

**Comment by EdwinTh** [comment]
Thank you for notifying, I will look into it as soon as time allows.

**Comment by EdwinTh** [comment]
Indeed some things were not implemented a bit odd, it was due to some legacy the as.character was still in there. Fixed it now. Thanks for pointing it out.
