### ISSUE TITLE
fill_by_function no parameters

### ISSUE THREAD

**Issue by EdwinTh** [EdwinTh/padr#2]
Because the ... is used to specify the column names I haven't figured out yet how it can also be used to specify optional parameters to fun.

**Comment by DavisVaughan** [comment]
If you aren't upset by a `purrr` dependency then boy do I have a solution for you. Change 1 line at the top to `fun <- purrr::as_mapper(fun)` and you now have all the power of the purrr `~` syntax.

```r
fill_by_function <- function(x,
         ...,
         fun = mean) {
  fun <- purrr::as_mapper(fun)
  if (! is.function(fun) ) {
    stop('fun is not a valid function', call. = FALSE)
  }
  
  is_df(x)
  
  inds <- get_the_inds(x, ...)
  
  for (i in inds) {
    val <- unlist( x[, i] )
    val_no_na <- val[!is.na(val)]
    value <- fun(val_no_na)
    
    if (length(value) > 1){
      warning('fun does return multiple values, only the first is used',
              call. = FALSE)
      value <- value[1]
    }
    
    val[is.na(val)] <- value
    x[, i] <- val
  }
  return(x)
}

```

Examples:

```r
fill_by_function(ex_df, y1, y2, fun = mean)
#> # A tibble: 363 x 3
#>    x             y1    y2
#>    <date>     <dbl> <dbl>
#>  1 2016-01-03  14.0  23.0
#>  2 2016-01-04  12.0  49.0
#>  3 2016-01-05  19.0  20.0
#>  4 2016-01-06  15.3  26.4
#>  5 2016-01-07  15.3  26.4
#>  6 2016-01-08  10.0  32.0
#>  7 2016-01-09  14.0  25.0
#>  8 2016-01-10  15.3  26.4
#>  9 2016-01-11  15.3  26.4
#> 10 2016-01-12  15.0  39.0
#> # ... with 353 more rows

fill_by_function(ex_df, y1, y2, fun = ~mean(.x, trim = .2))
#> # A tibble: 363 x 3
#>    x             y1    y2
#>    <date>     <dbl> <dbl>
#>  1 2016-01-03  14.0  23.0
#>  2 2016-01-04  12.0  49.0
#>  3 2016-01-05  19.0  20.0
#>  4 2016-01-06  15.4  26.9
#>  5 2016-01-07  15.4  26.9
#>  6 2016-01-08  10.0  32.0
#>  7 2016-01-09  14.0  25.0
#>  8 2016-01-10  15.4  26.9
#>  9 2016-01-11  15.4  26.9
#> 10 2016-01-12  15.0  39.0
#> # ... with 353 more rows

fill_by_function(ex_df, y1, y2, fun = ~sum(.x) / 4)
#> # A tibble: 363 x 3
#>    x             y1     y2
#>    <date>     <dbl>  <dbl>
#>  1 2016-01-03  14.0   23.0
#>  2 2016-01-04  12.0   49.0
#>  3 2016-01-05  19.0   20.0
#>  4 2016-01-06 766   1321  
#>  5 2016-01-07 766   1321  
#>  6 2016-01-08  10.0   32.0
#>  7 2016-01-09  14.0   25.0
#>  8 2016-01-10 766   1321  
#>  9 2016-01-11 766   1321  
#> 10 2016-01-12  15.0   39.0
#> # ... with 353 more rows
```

**Comment by DavisVaughan** [comment]
To be fair, you could always do this with the existing solution. It's a lot of boilerplate code compared to the purrr soln, but if you don't want to confuse people that don't use the tidyverse it might be preferred. 

```r
fill_by_function(ex_df, y1, y2, fun = function(.x) mean(.x, trim = .2))
```

**Comment by EdwinTh** [comment]
That is a very elegant solution, thanks! I am not worried about the dependency, however it enforces the user to use the purrr-style function specification. I am a bit on a cross roads currently, whether I want to fully commit to the tidyverse-style or not. I think I will carry this decision over the upcoming release which I want to wrap-up first.

**Comment by DavisVaughan** [comment]
Sounds good to me! I'm pretty tidyverse heavy myself, and hope to build out a number of time series / financial analysis tools for tidyverse users in the coming future. But I totally get wanting to have a great tool to help both camps!

**Comment by EdwinTh** [comment]
Chose to not devote `padr` completely to the tidyverse, going to leave the `fill_by_function ` function the way it is. It is not `padr`'s essence, it serves its purpose for simple cases. For more complicated cases there are great options in the tidyverse already present.
