### ISSUE TITLE
Use existing dataframe groups in pad

### ISSUE THREAD

**Issue by wdearden208** [EdwinTh/padr#21]
pad should allow for using existing groups in a data frame for the padding grouping.

As an example test, here is one lifted from a function I had written:

``` {r}
test_that("Pads months", {
    before <- tibble(
        site_id = c("A - a", "A - a", "B - b"),
        date = c(ymd(20141101), ymd(20150101), ymd(20140301)),
        division = c("A", "A", "B"),
        y = c(1, 2, 3)
    )
    after <- tibble(
        site_id = c("A - a", "A - a", "A - a", "B - b"),
        date = c(ymd(20141101), ymd(20141201), ymd(20150101), ymd(20140301)),
        division = c("A", NA, "A", "B"),
        y = c(1, NA, 2, 3)
    )
    expect_equal(after, before %>% group_by(site_id) %>% pad("month"))
})

```

It currently passes the following test:

``` {r}
test_that("Pads months", {
    before <- tibble(
        site_id = c("A - a", "A - a", "B - b"),
        date = c(ymd(20141101), ymd(20150101), ymd(20140301)),
        division = c("A", "A", "B"),
        y = c(1, 2, 3)
    )
    after <- tibble(
        site_id = c("A - a", "A - a", "A - a", "B - b"),
        date = c(ymd(20141101), ymd(20141201), ymd(20150101), ymd(20140301)),
        division = c("A", NA, "A", "B"),
        y = c(1, NA, 2, 3)
    )
    expect_equal(after, pad(before, "month", group = "site_id"))
})

```

**Comment by wdearden208** [comment]
I'm on mobile so I can't edit it easily but I meant that it passes the test with date as the first column.

**Comment by EdwinTh** [comment]
Interesting idea. My initial plan was to keep padr completely separate from dplyr, because it should work with other frameworks as well, like data.table. Thats why the grouping is parameter. On the other hand, it will be quite straightforward to go from the dplyr grouping to the group parameter. Will look into it soon.

**Comment by EdwinTh** [comment]
Implemented in the dev version. As well as maintaining the grouping on both `pad` and `thicken`
