### ISSUE TITLE
Error when grouping variable has NA

### ISSUE THREAD

**Issue by wdearden208** [EdwinTh/padr#23]
``` {r}
before <- 
        tibble(
            date = c(ymd(20141101), ymd(20150101), ymd(20150301)),
            group = c("A", "A", NA),
            y = c(1, 2, 3)
        )
```

If I run pad(before), I do not get an error but if I run pad(before, group = "group"), I get the following error:

Error in if (!all(dt_var[1:(length(dt_var) - 1)] <= dt_var[2:length(dt_var)])) { : 
  missing value where TRUE/FALSE needed

I see the same error on stackoverflow: http://stackoverflow.com/questions/16787038/r-insert-rows-for-missing-dates-times#comment73758691_41767386

**Comment by EdwinTh** [comment]
There is a new implementation of `pad`, that already resolved this issue. On the current development version you should not get this error anymore.

**Comment by wdearden208** [comment]
Ok thank you. My work computer prevents me from building from source so I was unable to test the development version.

**Comment by EdwinTh** [comment]
Use devtools::install_github("edwinth/padr")

**Comment by wdearden208** [comment]
Unfortunately it's a security/firewall issue. Not even hadley's solution (https://github.com/hadley/devtools/issues/877), downloading the source then building, or cloning the git and installing from that work.
