### ISSUE TITLE
Silencing Messages

### ISSUE THREAD

**Issue by rtaph** [EdwinTh/padr#31]
Hi @EdwinTh,

Thanks for a great package.

Quick question, have you thought of adding an option to silence messages from `pad()`? At the moment, the [source code](https://github.com/EdwinTh/padr/blob/master/R/pad.R#L208) prints a message "pad applied on the interval:" even when the interval is supplied as a function argument. What are your thoughts on removing this message if there is no ambiguity?

Thanks,

**Comment by edwinthoen** [comment]
Sounds reasonable. Will adjust it. Thanks
