### ISSUE TITLE
Better use of NSE in fill_by suite

### ISSUE THREAD

**Issue by EdwinTh** [EdwinTh/padr#32]
Just made some hacks have a `dplyr` feel to these functions, without real understanding. Make sure functions behave same as `dplyr`, possibly using `lazyeval` and `rlang` as dependencies.

[See questions like.](https://stackoverflow.com/questions/44619058/passing-unquoted-column-list-to-fill-by-function-in-padr)

**Comment by danielsjf** [comment]
Maybe best to wait until all the bugs are fixed (should be quite soon, judging from the github activity in dplyr, tidyverse and tidyselect). They are currently updating the way how NSE works in the tidyverse, but these new versions still feel a bit beta.

There is an excellent vignette on their new way of working:
https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html

**Comment by EdwinTh** [comment]
fill_by_suite now uses proper NSE
