### ISSUE TITLE
get_interval breaks with uninformative error when datetime variable contains NA

### ISSUE THREAD

**Issue by EdwinTh** [EdwinTh/padr#33]
https://stackoverflow.com/questions/44814135/inserting-row-in-missing-hourly-data-in-r-using-padr-package-weird-error

**Comment by coellom96** [comment]
This is the data set I was experiencing the error with.  It is hourly PM2.5 concentration data from the EPA. 
[hourly_81102_2015.zip](https://github.com/EdwinTh/padr/files/1117399/hourly_81102_2015.zip)

**Comment by EdwinTh** [comment]
Thanks @coellom96, the `get_interval` function now checks for missing values first and will break with an informative error.
