### ISSUE TITLE
options of omitting NA values in Date column

### ISSUE THREAD

**Issue by raymkchow** [EdwinTh/padr#34]
https://stackoverflow.com/questions/44814135/inserting-row-in-missing-hourly-data-in-r-using-padr-package-weird-error/44838022#44838022

Error occurs in pad when there are NAs in the date/POSIX column in a data.frame. Can we have an option of removing the NA values in padding?

**Comment by EdwinTh** [comment]
Thank you very much for notifying me. I did see the question too and made some changes to the code last week (see solved issue #33).  The function now throws an informative error when the datetime variable contains NA values. I think removing the NA valued rows from a df is out of scope for padr. You should use dplyr for that, like

df %>% filter(!is.na(timestamp)) %>% pad

However, I am thinking of allowing NA values in the datetime variables and returning the rows with the NA values in addition to the padded dataset.
