### ISSUE TITLE
pad_int

### ISSUE THREAD

**Issue by akitepowell** [EdwinTh/padr#40]
This is a very helpful package, and I plan to incorporate it into much of my R work.  I was just trying out pad_int, and had an issue with it working with an object that was:
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	12 obs. of  2 variables:
The error I got was:
Error: is.numeric(int_var) is not TRUE.  

However, when I took the same data frame and converted it to just a data frame it worked as expected.
Thanks,
Aaron

**Comment by EdwinTh** [comment]
That is a bug, I can reproduce it. Thanks for the notification.

     x <- data_frame(int = c(1:4, 7), rnorm(5)) 
     x %>% pad_int("int")
     x %>% as.data.frame() %>% pad_int("int")
