### ISSUE TITLE
Pad() returns an object missing error for data frames larger than 1 million rows

### ISSUE THREAD

**Issue by danielsjf** [EdwinTh/padr#44]
It didn't work before (the version on CRAN returned a normal error message), but I guess one of the variables to generate the error message is now missing in the development version.

(reprex compatible)
```
library(tidyverse)
library(padr)
x <- expand.grid(date = ISOdate(2017:2025,1,1,0), item = 1:20) %>% group_by(item) %>% pad('hour')
```

Error:
```
Error in sprintf("Estimated %s returned rows, larger than %s milion in break_above",  : 
  object 'break_above' not found
```

Will you support more than 1 million lines in the future? I could live with longer process times.

**Comment by danielsjf** [comment]
I think the following lines:
https://github.com/EdwinTh/padr/blob/ee118b995fbbcc72e9b5b1be2db7ae8562af038a/R/pad.R#L402-L406

Should become

```
  threshold <- threshold * 10 ^ 6
  if (n > threshold) {
    stop(sprintf("Estimated %s returned rows, larger than %s milion in break_above",
                 n, threshold), call. = FALSE)
  }
```

Actually only break_above on the last line should be replaced by threshold.

**Comment by EdwinTh** [comment]
Coincedently noticed it myself too this morning, thanks for the fix!

**Comment by EdwinTh** [comment]
"Will you support more than 1 million lines in the future? I could live with longer process times."

It is the parameter `break_above`, so if you want more rows you can.

**Comment by danielsjf** [comment]
My bad, I didn't see the exposed argument :-) Thanks!
