### ISSUE TITLE
thicken() to handle NA values better

### ISSUE THREAD

**Issue by foundinblank** [EdwinTh/padr#47]
I have several date-time columns, and some of them have `NA` values. Using thicken() breaks when I try it on those columns with `NA` cells, but works fine on columns with no `NA` cells. 

This is the error I get: 
`Error in if (unique(nchar(x_char)) == 10) { : `
`  missing value where TRUE/FALSE needed`
`In addition: Warning message:`
`In if (unique(nchar(x_char)) == 10) { :`
`  the condition has length > 1 and only the first element will be used`

**Comment by EdwinTh** [comment]
This is already been fixed for v.0.4.0. You can ialready nstall the dev version which is becoming stableish.

**Comment by foundinblank** [comment]
Awesome! This is such a great package. Thanks.
