### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by peeyooshc** [EdwinTh/padr#48]
Thank you for this excellent package - it has saved me a lot of time in getting timeseries to be padded out correctly.

I think it would help others if your vignette and examples also showed how it can be used to pad grouped variables as in this article https://www.r-bloggers.com/padrpad-does-now-do-group-padding/.

Greatly improved my understanding and ability to use it.

- PC

**Comment by EdwinTh** [comment]
Thanks for pointing this out. Indeed the vignette hasn't been properly updated since v0.1.0. I will give it a thorough revision for v0.4.0.
