### ISSUE TITLE
add thicken() argument to drop original date column

### ISSUE THREAD

**Issue by foundinblank** [EdwinTh/padr#55]
A snazzy thicken() feature would be an argument to drop the column that was just thickened. Can call it `drop` and have it set to `FALSE` by default. When `drop = TRUE`, the column that was thickened is removed at the end of the function.

**Comment by EdwinTh** [comment]
Thanks, that shouldn't be too much trouble to implement.

**Comment by EdwinTh** [comment]
Reopening, because it was lost in a patch release and I made a mistake in the branching. Needs to be added again.
