### ISSUE TITLE
padr-package.R no longer needed

### ISSUE THREAD

**Issue by EdwinTh** [EdwinTh/padr#6]
@schloerke 

Barret you added this file to fix a namespace issues. dplyr is no long used in the source code, therefore I think it is more appropriate to move it to suggests in the DESCRIPTION. It can also be removed from the NAMESPACE, which means removing this file, correct?

**Comment by schloerke** [comment]
Correct! Good spot!


I would also pick a single place for data.table to exist. Either suggests
or imports, but not both.

The way it's currently set up, I would have it as a suggests as it's only
used for one line in thicken.R (and tests). Between lines 131 and 132 in
thicken.R, try to load it with `if(!requireNamespace("data.table"))
stop("blah")` and then continue to use it with `::` like like in 132.

Couldn't line 131 also be `if(inherits(original, "data.table")) ...` ? It
achieves the same thing, but reading it is clearer.

**Comment by EdwinTh** [comment]
inherits indeed is better, didn't know about that function

Adding the if(!requireNamespace("data.table")) indeed is good practise under most circumstances, but I think it is redundant here. When if (inherits(original, "data.table")) is TRUE, !requireNamespace("data.table") must be FALSE and therefore the stop() will never be reached...

**Comment by schloerke** [comment]
Ah! You're correct.  No need to add the check. :-)
