### ISSUE TITLE
padr not available for R version 3.3.2

### ISSUE THREAD

**Issue by soedr** [EdwinTh/padr#7]
Hi there,

First off thanks for putting this package together, looks very helpful. I wasn't able to install using 

     > install.packages('padr') 
        Warning in install.packages :
           package ‘padr’ is not available (for R version 3.3.2)

The package does, however, install perfectly fine with `devtools::install_github()`

**Comment by EdwinTh** [comment]
I don't think it is due to the R version, the version is always mentioned when a package can't be found. 
But then I don't know why it is not installing, installation was tested with the R CMD check on all three main operating systems.  You are still able to install other package, it is just padr that is not found?

**Comment by soedr** [comment]
Yes, everything else works fine, and it installs with `devtools::github_install()`, so it's not a big issue from my point of view. I just wanted to bring it to your attention, in case other people might face this issue. Let me know if you need more info from my side.

**Comment by EdwinTh** [comment]
Yeah, thanks. If you could please tell me what os you are on I see if others have problems too.

**Comment by notiv** [comment]
Just FYI: I had the same issue on Windows 8, R 3.3.1. github_install() worked.

**Comment by EdwinTh** [comment]
Thanks for notifying. I will look into it.

**Comment by EdwinTh** [comment]
Please consult the following, hopefully this will resolve your issues

http://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa
