### ISSUE TITLE
warning re: `as_data_frame()`

### ISSUE THREAD

**Issue by MattCowgill** [EdwinTh/padr#72]
When  I use `padr::pad()`, I get the following warning:

```
Warning message:
`as_data_frame()` is deprecated as of tibble 2.0.0.
Please use `as_tibble()` instead.
The signature and semantics have changed, see `?as_tibble`
```

The backtrace shows that `padr::set_to_original_type()` calls `dplyr::as_data_frame(x)`, which is deprecated.

Thanks for the package, it's great

**Comment by EdwinTh** [comment]
Thanks, yes this is due to a recent update to the `tibble` package. It was pointed out to me by the CRAN maintainers as well. A patch release is on its way to CRAN.
