### ISSUE TITLE
Broken links / previews?

### ISSUE THREAD

**Issue by modche** [EdwinTh/padr#79]
Are the links to the vignettes broken? Thanks.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/13642619/104300123-5cac8500-54c6-11eb-8246-04028a0fc188.png">

**Comment by EdwinTh** [comment]
Not sure what you are referring to, the official CRAN vignettes seem fine (https://cran.r-project.org/web/packages/padr/vignettes/padr.html)

Could you explain some more if this is not what you mean? Thanks

**Comment by modche** [comment]
Sorry, my screenshots links to the readme.md here in the repos. At the end are two links to rmd files. Should these links not go to html knitted files?

**Comment by EdwinTh** [comment]
Ah, that is a good idea. Links do now point to the compiled vignettes on CRAN. Vielen Dank!
