### ISSUE TITLE
.dots deprecated

### ISSUE THREAD

**Issue by MattCowgill** [EdwinTh/padr#80]
`padr:::set_to_original_type()` invokes `dplyr::group_by()` and calls the `.dots` argument of `group_by()`. That argument was deprecated in dplyr 1.0.0. Using `padr::pad()` now throws up a warning message about this deprecation. 

The relevant line: https://github.com/EdwinTh/padr/blob/26cfba907d5c8ff5536862e5a55643dc8fd1e818/R/thicken.R#L148

**Comment by EdwinTh** [comment]
Thanks for spotting this. Will fix it

**Comment by kgjerde** [comment]
Sorry about the unintended noise. That commit does *not* fix the issue. However, to change the line to

`x <- dplyr::group_by(x, dplyr::across(grps))`

seems to do the trick (see tidyverse/dplyr#4734). I have not run the test suite, however.

**Comment by EdwinTh** [comment]
Thanks for looking into it. I must admit it fell of my radar, will look into it soon.

**Comment by EdwinTh** [comment]
This is now fixed and will be released soon. Thanks for the help!

**Comment by MattCowgill** [comment]
Thanks for a great package @EdwinTh
