### ISSUE TITLE
Allow no thickening if the "interval" is "too short"

### ISSUE THREAD

**Issue by Fuco1** [EdwinTh/padr#84]
I think this check makes no sense.  What if randomly my sales data only happen to be one sale on each 1st day of the month and I'm thickening to a month to perform monthly aggregates.  It just crashed my pipeline so it's not just theoretical example :D

https://github.com/EdwinTh/padr/blob/f960e4604346e138d819083d7754f7030d648cfa/R/thicken.R#L128-L131

**Comment by EdwinTh** [comment]
Thanks for notifying me. I will look into it soon.
