### ISSUE TITLE
group

### ISSUE THREAD

**Issue by youngday2** [EdwinTh/padr#85]
I am getting the following error and seems like its an issue with group.
R Error: start value is larger than the end value for all groups.

You can find reproducible example here
https://stackoverflow.com/questions/69726957/pad-data-prior-to-start-date-and-after-end-date-in-r

If only one site is evaluated the function works as intendended 

thanks

**Comment by EdwinTh** [comment]
I see what you want to do now. There is no grouping on these arguments, you can only file a start and an end date for all the groups. If you want to use different start and end values for the groups, then you have to apply that yourself. I believe you did it yourself already in the SO post.

I will update the docs at the next release that there is no grouping on start and end date arguments, to make it clear that this is not working the way you expected it to work. Thanks for filing the issue.

**Comment by youngday2** [comment]
Thanks Edwin.
